In [1]:
import numpy as np

In [2]:
# create death data and convert to an array
deaths_data = [[344, 2345], [4345, 253]]
deaths_array = np.array(deaths_data)

In [3]:
print(deaths_array[0, 0])
print(deaths_array[1,0])

344
4345


U.S. Deaths: 344 and 4345

In [4]:
print(deaths_array[0, 1])
print(deaths_array[1,1])

2345
253


G.B. Deaths: 2345 and 253

In [5]:
print(deaths_array[1,1])

253


GB deaths in 2nd battle: 253

In [6]:
deaths_array.sort(0)

[[ 344  253]
 [4345 2345]]

In [7]:
deaths_array.sort(1)

[[ 253  344]
 [2345 4345]]

In [8]:
print(deaths_array.T)

[[ 253 2345]
 [ 344 4345]]


[[ 253 2345]
 [ 344 4345]]

In [9]:
deaths_array.sum()

7287

Sum of all deaths: 7287

In [10]:
# redefining the array
deaths_array = np.array(deaths_data)

In [11]:
deaths_array[1,1] = 2349

Array with updated battle 2 GB deaths.
array([[ 344, 2345],
       [4345, 2349]])